jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
  workspace:
    clean: all
  variables:
  - name: buildConfiguration
    value: 'release'
  - name: buildPlatform
    value: 'anycpu'
  - group: BUILD Management Resources

  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_SFA-DAS-EarlyConnect-Jobs

  - task: DotNetCoreCLI@2
    displayName: 'Student Data Import Function'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.EarlyConnect.Functions/SFA.DAS.EarlyConnect.Functions.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'
